# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'xxChat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for xxChat

  target 'xxChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'xxChatUITests' do
    # Pods for testing
  end
  
  pod 'JMessage'
  
  pod 'SDAutoLayout'

end
